service:
    path_pidfile: /var/run/buoy/
    start_timeout: 1

database:
    database: boyadb
    user: username
    password: password
    host: localhost

serial:
    port: /dev/ttyUSB0
    baudrate: 115200
    stopbits: 1
    parity: N
    bytesize: 8
    timeout: 0

mqtt:
    broker_url: redmic.es
    client_id: granadilla-buoy-current-meter
    topic_data: redmic/activity/1286
    username: username
    password: changeme
